### ISSUE TITLE
Scroll issue on homepage

### ISSUE THREAD

**Issue by lllama** [starfederation/datastar#113]
Scrolling the homepage in Safari has an odd bug. I'm guessing there's some updates coming from the server that cause the browser to scroll to the top of the TODO list. If you scroll quickly enough then you can get to the bottom. (Also exhibits the same behaviour coming from the bottom to the top.)

https://github.com/user-attachments/assets/c26ef6a9-fb21-4bad-b0b5-26192ddd0396

**Comment by delaneyj** [comment]
Is it iOS?  Money says this is in Safari

**Comment by lllama** [comment]
So just to add to the fun, this only seems to happen if you add something to the todo list.

**Comment by delaneyj** [comment]
Fixed with latest update
