### ISSUE TITLE
Cannot set properties of undefined error when attempting to use Custom Header

### ISSUE THREAD

**Issue by nzanghi-tst** [starfederation/datastar#115]
I was trying to see what custom headers looked like in action, and ran into this issue. My component block triggering the problem looks like the following:
```html
<div
  id="root"
  class="flex flex-row h-screen max-w-full"
  data-on-load="$$get('/endpoint')"
  data-header-X-My-Header="myheader"
  data-store={ templ.JSONString(store) }
></div>
```

I believe I am not doing anything explicitly incorrectly based off of the docs

I traced the issue to the following lines:
https://github.com/delaneyj/datastar/blob/5c0865d4a6a54a7162ef77d229092888b9d2fe66/packages/library/src/lib/plugins/backend.ts#L53-L55

the destructured `headers` variable is the main culprit. After trying a quick fix of adding `_value` to see what would happen next, I got an `Error evaluating Datastar expression` error message that seems to indicate my custom header is being evaluated as a variable

**Comment by nzanghi-tst** [comment]
Using a template literal seemed to alleviate the evaluation error:

```html
<div
	data-header-X-My-Header="`this is a test`"
>
```

I also was able to see the custom header in my network request with the following changes:

Changed the onLoad of the HeadersPlugin on L50 of `src/lib/plugins/backend.ts` to use an Object instead of a map, also pulling the headers off `s._dsPlugins.fetch` with the `value` attribute
```js
onLoad: (ctx) => {
    ctx.upsertIfMissingFromStore('_dsPlugins.fetch', { headers: {} })
    const s = ctx.store()
    const { headers } = s._dsPlugins.fetch.value
    const key = ctx.key[0].toUpperCase() + ctx.key.slice(1)
    headers[key] = ctx.reactivity.computed(() => ctx.expressionFn(ctx))
    return () => {
      delete headers[key]
    }
  },
```

Changed the logic around adding headers to the fetcher on L283:
```js
  if (
    req.headers &&
    store?._dsPlugins?.fetch?.value?.headers &&
    Object.keys(store?._dsPlugins?.fetch?.value?.headers).length > 0
  ) {
    for (const key in store?._dsPlugins.fetch.value.headers) {
      const value = store._dsPlugins.fetch.value.headers[key].value
      req.headers[key] = value
    }
  }
```
^ edited, Object.keys did not like headers being undefined

**Comment by delaneyj** [comment]
```html
<div data-header-X-My-Header="`this is a test`">
```

This is correct, remember data-* plugins are evaluated JS via sandbox constructors.  The previous is like saying `x = this is a test` in JS.  I'll get into the weeds and get a general fix for including the headers properly.  It's a rarely use feature and has been ignored for a bit.

Thanks for the report and will get back to you!

**Comment by delaneyj** [comment]
@nzanghi-tst I'm considering remove the plugin for `data-header-*`.  For me it's a vestiage of the old port trying to be 1:1 with HTMX.  Since its SSE first now and you still can use cookies I don't think this is needed.  Agree?

**Comment by nzanghi-tst** [comment]
I think I am in agreement. Most use cases I can think of can be solved via cookies or browser storage.

One scenario I am struggling with is authentication (exchanging security headers on an auth server, for example), but my guess is that that should be handled by a workflow outside of datastar completely and the session state should be updated on whatever backend server and then pushed forward via SSE

**Comment by delaneyj** [comment]
That's exactly right, if you are in Go I suggest [goth](https://github.com/markbates/goth).  That should do a normal Oauth2 (or whatever) flow and leave you with a cookie with just the ID of the user which then you'd fill with info in some backend lookup (like NATS's KV)

**Comment by delaneyj** [comment]
Removed and bump version to 0.17.0
