### ISSUE TITLE
localStorage feature query/request

### ISSUE THREAD

**Issue by alecgargett** [starfederation/datastar#118]
Hi Delaney. I love your work with datastar.

I've noticed that one thing you can do with hyperscript, Alpine and vanilla JS (and heavy SPA frameworks) that you can't do with HTMX or unpoly is putting something in localStorage.
For example you could code a dark mode button and put the dark mode state into localStorage with hyperscript or Alpine but not with HTMX. I assume data-star is like HTMX in this respect?

This isn't a big deal because one can just use vanilla JS for that, but I'm wondering if you see any possible benefit to adding this functionality to datastar itself?

**Comment by delaneyj** [comment]
Yep, check out the offline/online sync demo.  It's storing the store to localStorage.  If you have specific issue please let us know.  Also best to talk about your needs on the Discord channel

**Comment by alecgargett** [comment]
Ah. I messed up my search. Thanks.
