### ISSUE TITLE
datastar-remove event does not handle useViewTransition or settleDuration.

### ISSUE THREAD

**Issue by SpiralOSS** [starfederation/datastar#13]
The datastar-remove event does not handle useViewTransition or settleDuration.

If neither is provided then it works properly.
If one or both are provided then Datastar will repeat the request every second over and over, receiving the same response.

(It appears like the variables are swept up into the selector or paths.)

**Comment by bencroker** [comment]
@delaneyj the `datastar-remove` event never supported settling and view transitions. Should it, or does the spec need to be adjusted?

**Comment by bencroker** [comment]
@SpiralOSS I’ve cheated a bit and added the cases with TODO comments, so `settleDuration` and `useViewTransition` will have no effect but won’t break your tests.
https://github.com/starfederation/datastar/blob/650107ddeb8c20d5a30e35da3f1dee175ce18b29/code/ts/library/src/plugins/actions/backend/sse.ts#L289-L294
