### ISSUE TITLE
Discrepancy between SDK spec and Doco with useViewTransition default

### ISSUE THREAD

**Issue by SpiralOSS** [starfederation/datastar#14]
The docs says that useViewTransition (which is still 'vt' here) defaults to true
https://github.com/starfederation/datastar/blob/3a50662311d7f2725418d4ad69d0fb3aca6929cc/code/go/site/static/md/reference/plugins_backend.md?plain=1#L58

The SDK says that useViewTransition defaults to false
https://github.com/starfederation/datastar/blob/3a50662311d7f2725418d4ad69d0fb3aca6929cc/design/SDK.md?plain=1#L144

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/starfederation/datastar/commit/6fedc143712a60180137ea9a3766f709ed59f8a4.
