### ISSUE TITLE
Signal names of length 1 fail to be evaluated

### ISSUE THREAD

**Issue by ronnieoverby** [starfederation/datastar#141]
Repro:

https://jsfiddle.net/jrmeaphz/

```HTML
<div data-store='{ "x":123 }'>
    <input type="number" data-model="x">
    <span data-text="$x"></span>
</div>
```

Error:

> Error evaluating Datastar expression:
>   return $x
> Error: $x is not defined
> Check if the expression is valid before raising an issue.

**Comment by delaneyj** [comment]
Fixed in v0.18.6
