### ISSUE TITLE
Can we get a super simple example for the README, and link to the documentation?

### ISSUE THREAD

**Issue by coolaj86** [starfederation/datastar#144]
From the conference talk and the podcast I get the "why", but I have no idea of the "how" or "what".

I need the full-loop hello world.

Either how do I run an example locally against a public demo server,

Or how do I set up a basic express server serving the hello world from the public folder.

I'm completely outside the loop of the htmx community. I don't even do frontend (when I can avoid it).

I'd love to see a header section.

## Documentation

- Quick Start: [link]
- Guide: [link]
- API: [link]
- Examples: [link]

**Comment by delaneyj** [comment]
PRs welcomed in this department.  

I just did https://github.com/delaneyj/realworld-datastar which a more of a basic "normal" app.  Does this help or is it too much other stuff.

In general Datastar should/will be a tiny part of your app and will just get out of your way.  

Please join the Discord and let's talk!

**Comment by delaneyj** [comment]
I'm gonna close soon @coolaj86 if I don't hear back

**Comment by coolaj86** [comment]
@delaneyj I'm not qualified to create those examples, because I don't have enough information to know what I would be doing.

**Comment by coolaj86** [comment]
For example, in the link you gave there's no information about how to run the server:

https://github.com/delaneyj/realworld-datastar

It looks like the Get Started section was copied from another repo (go-task).

For a go repo I would expect something like

> ## Getting Started
> 
> Build and run the project like this:
> 
> ```sh
> go generate ./...
> go run <the thing>
> ```
> 
> You can connect on the default port at:
>   - <http://localhost:3000/>
> 

But even that is getting ahead. What's the Hello World? What's the smallest unit of _the thing_ that this does?

Something like

> ## Install Datastar JavaScript
> 
> ```sh
> npm install --save datastar
> ```

> `./public/hello.html`:
> ```html
> <html>
>   <head> ... </head>
>   <body>
>     <div data-define-target="message"></div>
> 
>     <form>
>       <label>Foo:
>         <input type="text" name="foo" value="bar" />
>       </label>
>       <button data-do-a-thing="POST /views/that-tickles" data-to-a-target="message">Tickle Me!</button>
>     </form>
> 
>     <script src="./assets/datastar.js"></script>
>   </body>
> </html>
> ```
> 
> `./serve.go`:
> ```go
> router.handle(`POST /views/`, func (w http.Writer, r *http.Request) {
>   w.Write(fmt.Sprintf(`That tickles. %s!`, r.Query.Get("foo")))
> })
> ```
> 
> ```sh
> go run ./serve.go
> ```

**Comment by delaneyj** [comment]
How about something like this article @coolaj86? https://dev.to/blinkinglight/golang-data-star-1o53 by @blinkinglight
