### ISSUE TITLE
Bug: multi-line fragments do not strip the `fragment `  prefix from consecutive fragment lines

### ISSUE THREAD

**Issue by pdf** [starfederation/datastar#165]
When sending multi-line fragments (per #40 #41) the `fragment ` prefix is not stripped from consecutive fragment lines in the message, resulting in spurious output to the DOM.

This appears to be thanks to:

https://github.com/delaneyj/datastar/blob/45223e9728a4e7cbf8f0e1bf4950f26887840803/packages/library/src/lib/plugins/backend.ts#L185

Since the slicing of the line to remove the prefix happens inside this condition, which won't process consecutive fragment lines.

We could probably move the slice outside this condition, but it's not clear to me why we would otherwise want to skip processing of consecutive lines with the same datatype.

If this condition is only for handling multi-line fragments, I think we can remove it and just append to `fragment` inside the `switch` without any special handling:

```diff
diff --git a/packages/library/src/lib/plugins/backend.ts b/packages/library/src/lib/plugins/backend.ts
index 8ae40cd..749713f 100644
--- a/packages/library/src/lib/plugins/backend.ts
+++ b/packages/library/src/lib/plugins/backend.ts
@@ -166,8 +166,7 @@ async function fetcher(method: string, urlExpression: string, ctx: AttributeCont
             settleTime = DEFAULT_SETTLE_TIME,
             useViewTransition = DEFAULT_USE_VIEW_TRANSITION,
             exists = false,
-            selector = '',
-            currentDatatype = ''
+            selector = ''
 
           for (let i = 0; i < lines.length; i++) {
             let line = lines[i]
@@ -175,12 +174,10 @@ async function fetcher(method: string, urlExpression: string, ctx: AttributeCont
 
             const firstWord = line.split(' ', 1)[0]
             const isDatatype = knownEventTypes.includes(firstWord)
-            const isNewDatatype = isDatatype && firstWord !== currentDatatype
-            if (isNewDatatype) {
-              currentDatatype = firstWord
+            if (isDatatype) {
               line = line.slice(firstWord.length + 1)
 
-              switch (currentDatatype) {
+              switch (firstWord) {
                 case 'selector':
                   selector = line
                   break
@@ -195,6 +192,7 @@ async function fetcher(method: string, urlExpression: string, ctx: AttributeCont
                   settleTime = parseInt(line)
                   break
                 case 'fragment':
+                  fragment += line + '\n'
                   break
                 case 'vt':
                   useViewTransition = line === 'true'
@@ -203,8 +201,6 @@ async function fetcher(method: string, urlExpression: string, ctx: AttributeCont
                   throw new Error(`Unknown data type`)
               }
             }
-
-            if (currentDatatype === 'fragment') fragment += line + '\n'
           }
 
           if (!fragment?.length) fragment = '<div></div>'
```

**Comment by bencroker** [comment]
The line `data: fragment` should only appear once per fragment event. While multiple top-level elements are allowed in the fragment event, they should all follow `data: fragment`.

**Comment by delaneyj** [comment]
@bencroker is right!

**Comment by pdf** [comment]
To confirm my understanding, you're suggesting that given this template output:

```html
<div
  id="blah" />
```

The event data should look like the below?

```
data: fragment <div
data:   id="blah" />
```

**Comment by bencroker** [comment]
Correct, although I usually output it as:
```
data: fragment
data: <div id="blah" />

```

**Comment by pdf** [comment]
Thanks. The example was a little contrived, but entirely possible depending on template engine/inputs.

**Comment by colmanhumphrey** [comment]
does that mean the ADR is mistaken here?

https://github.com/starfederation/datastar/blob/03d36e849c0084d17874261b66f98f2d9e964dd2/sdk/README.md?plain=1#L98-L122

**Comment by colmanhumphrey** [comment]
Oh I think I see, I guess the ADR is correct, and it's this issue that is out of date
