### ISSUE TITLE
Sync Golang and JavaScript versions

### ISSUE THREAD

**Issue by blinkinglight** [starfederation/datastar#173]
Currently, the version needs to be tracked manually with the existing [helpers](https://github.com/delaneyj/datastar/blob/d19126d70c568b54282a7deac8cd546ce04b5153/templ_templates.templ). It would be helpful if the datastar Go package could automatically inject its version into the CDN JavaScript include, ensuring the Golang package version remains in sync with the JavaScript version used.

**Comment by delaneyj** [comment]
This will be addressed in the new build process... By using esbuild as a library I'm also autogenerating https://github.com/starfederation/datastar/blob/main/code/go/sdk/version.go
