### ISSUE TITLE
Location Of Website Chart Titled "File Size (Hello World) first load"

### ISSUE THREAD

**Issue by human154** [starfederation/datastar#179]
I tried to find the source for the chart shown on the website (https://data-star.dev/) titled "File Size (Hello World) first load" but couldn't find it...  Is it available to me? ...If so could you please direct me to it?

**Comment by blinkinglight** [comment]
https://github.com/delaneyj/datastar/blob/main/backends/go/site/routes_home.go#L96 and route /chart ( https://data-star.dev/chart )

**Comment by human154** [comment]
Thank you!!!
