### ISSUE TITLE
fix docs or rename onlyIfMissing

### ISSUE THREAD

**Issue by blinkinglight** [starfederation/datastar#196]
the code: https://github.com/delaneyj/datastar/blob/main/packages/library/src/lib/plugins/backend.ts#L264
the docs: https://github.com/delaneyj/datastar/blob/main/backends/go/site/static/md/reference/plugins_backend.md ( ifmissing false )

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/delaneyj/datastar/pull/198.
