### ISSUE TITLE
File Upload example failing when sending bigger files

### ISSUE THREAD

**Issue by rael346** [starfederation/datastar#207]
On the [File Upload Example](https://data-star.dev/examples/file_upload), when I tried to upload a file bigger than 4MB (the limit set in the backend) no error appeared on the frontend and the browser console looks like this
<img width="677" alt="image" src="https://github.com/user-attachments/assets/80257c36-bdec-4105-8dcd-bf6d3077314f">
The [backend code](https://github.com/delaneyj/datastar/blob/main/backends/go/site/routes_examples_file_upload.go) implies that it will send an error message back to the user but for some reason the sse format is wrong based on the error message above.

**Comment by delaneyj** [comment]
That example might be ina bad state, thanks for bringing it up.  I did put severe limits on the upload to stop bad actors but the UI should reflect that.  Thank you for letting me know!

**Comment by delaneyj** [comment]
THis should be fixed in v0.20.0
