### ISSUE TITLE
Feature Request: Support plain HTTP responses

### ISSUE THREAD

**Issue by codepilotsf** [starfederation/datastar#210]
SSE is so cool. The ability to fire off multiple responses to the same request for example to show an optimistic update while waiting for a database operation is amazing.

But for many would-be Datastar users, I suspect this might be an extra impediment to adoption. For example, I wanted to use Datastar with AstroJS – but Astro has kind of weird support of SSE and would have required some awkward workarounds. 

Imagine how much simpler the docs would be if there was no SSE setup. Just return a response and the elements with matching DOM IDs get swapped in. Other meta data like merge type and selector could be set as custom response headers.

So then for users who want the added benefits of using SSE, they could opt in – or maybe Datastar could even be smart enough to handle both plain HTTP responses and SSE responses transparently? That would be super cool.

**Comment by bencroker** [comment]
What backend are you using with Astro?

**Comment by codepilotsf** [comment]
Astro is now full-fledged SSR framework. So the backend is Astro.

**Comment by delaneyj** [comment]
> Imagine how much simpler the docs would be if there was no SSE setup. Just return a response and the elements with matching DOM IDs get swapped in. Other meta data like merge type and selector could be set as custom response headers.

I understand the sentiment, but no.  If you want to do a "standard" fetch you should implement it and see all the issues you'll run into as you scale up.  Datastar has **one** way to learn and it works for CRUD to real-time apps. 
If you want this feature, make a plugin.  I know it's possible cause I did it already.  I originally created Datastar as a HTMX alternative, ported everything over and didn't even commit it.  IMO, it's a bad idea, especially now that we are getting official SDKs for every language to simplify this.
