### ISSUE TITLE
Add favicon and meta tags

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#217]
Add favicon and meta tags for sharing on social media to the website.

**Comment by bencroker** [comment]
Can you help with this, @khalwat ?

**Comment by delaneyj** [comment]
I'll make it part of the tsbuild, building all the different sizes if missing assign back to me

**Comment by delaneyj** [comment]
Actually @khalwat I don't know what @bencroker meant by the meta tags.... Advise and I can do the work to automate what I can.

**Comment by bencroker** [comment]
Done via https://github.com/starfederation/datastar/pull/257.
