### ISSUE TITLE
Upsert consistent ID for `data-indicator`

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#223]

**Comment by bencroker** [comment]
@delaneyj is there anything we can do to remove the requirement for elements using `data-indicator` to have an ID, without having to wait for an Idiomorph fix or port? Could the plugin add an ID to the element if one doesn't already exist? It's not ideal but feels like the right kind of magic to help prevent people getting tripped up by this anomaly.

**Comment by delaneyj** [comment]
Let me gaze into my orb for a bit
