### ISSUE TITLE
Website navigation is broken on Firefox

### ISSUE THREAD

**Issue by bshankar** [starfederation/datastar#224]
Hi I really love datastar. Thank you for making such an awesome framework!

The recent update seems to have broken all the links on the website. I was able to replicate this on mobile Firefox as well (no addons). I have attached a screenshot with network inspector open to show what happens when I click `get started`.

3rd row returns 302 response.
4th row shows `NS_BINDING_ABORTED` and goes back to the current URL.

Firefox version: 132

![Screenshot from 2024-11-22 16-52-34](https://github.com/user-attachments/assets/97c8f135-0e08-4868-98f0-82a84662bad7)

**Comment by delaneyj** [comment]
@bshankar thanks!  I've been trying locally with FF on Android and Linux Desktop (PopOS) and I can't reproduce.  Maybe join the discord and we can figure it out in a debug session.  Definitely want things to work in prep for v1!
