### ISSUE TITLE
Full on double streaming SSEs in Safari

### ISSUE THREAD

**Issue by SpiralOSS** [starfederation/datastar#226]
Discovered using Safari 17.6 (19618.3.11.11.5) on macOS Sonama Version 14.6.1 (23G93).

I can get two `updates` streams when viewing the [Bad Apple](https://data-star.dev/examples/bad_apple) video by doing the following:
1) going to that page
2) entering google.com in the address bar to browse there
3) waiting a second
4) clicking back

https://github.com/user-attachments/assets/b3eab2e0-0629-4abe-b4c8-45c28f2d7ffc

**Comment by delaneyj** [comment]
I don't have a Mac so it's really hard to test, debug this... can you get it to happen in Linux?

**Comment by SpiralOSS** [comment]
Unfortunately, I think this is a Safari-only issue.
The good news is that I was able to remedy this by using this block of Javascript:
```
window.onpageshow = function (event) {
    if (event.persisted) {
        window.location.reload();
    }
};
```
- [StackOverflow post](https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked)

The other suggestions did not fix it, i.e. `body on unload=""` and the additional directives on the cache-control header.

I don't know if you want to slip a Safari-only block to run this code in the lib; not sure what else it might effect.

**Comment by delaneyj** [comment]
It's at the app level, not Datastar, but I'll add to the site.  We may need a `data-safari-is-the-modern-ie6` plug-in to poly fill

**Comment by delaneyj** [comment]
For future reference it'll look like `data-on-pageshow.window="evt?.persisted && window.location.reload()"`.  It may not be a datastar issue but it definitely can be fixed with it :-)
