### ISSUE TITLE
data-replace-url is not working as expected

### ISSUE THREAD

**Issue by freefalling** [starfederation/datastar#229]
I've tried something like this:

```
<button
    data-store="{targetPage: 2, targetSize: 10}"
    data-on-click="$get('/envios/lista/fragment?page=' + $targetPage + '&pageSize=' + $targetSize)"
    data-replace-url="'/envios/lista?page=' + $targetPage + '&pageSize=' + $targetSize"
>
    Load Page 2
</button>
```

And expected the URL to be replace after I click the button, but it's getting replaced everytime the page loads. Is there a way to trigger replaceUrl only when some user action happens, like in this case a click over that button?

**Comment by bencroker** [comment]
This is the expected behaviour. Add the attribute in your SSE response, rather than on initial page load, if you want it to replace only on the `$get` action.

**Comment by freefalling** [comment]
Sorry I'm struggling to understand the DataStar GO SDK code, what should be the correct method to use? I'm trying with in my corresponding handler.go:

```
type urlSignal struct {
    ReplaceUrl string `json:"replace-url"`
}
```

Then somewhat below:


```
httpHandler := func(w http.ResponseWriter, r *http.Request) {
    sse := datastar.NewSSE(w, r)
    err := sse.MergeFragmentTempl(fragments.DataGrid(
        result.Shipments,
        result.TotalItems,
        page,
        pageSize,
    ))
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }

    err = sse.MarshalAndMergeSignals(urlSignal{
        ReplaceUrl: fmt.Sprintf("/envios/lista?page=%d&pageSize=%d", page, pageSize),
    })
    if err != nil {
        http.Error(w, err.Error(), http.StatusInternalServerError)
        return
    }
}
```

The fragment is getting swapped but I have zero signal attribute in SSE response related to the url replacement.

**Comment by bencroker** [comment]
What I meant is to add the data attribute to a merged fragment, or upsert the attribute into an existing fragment.

**Comment by freefalling** [comment]
That was amazing, I follow your advice and implement something like this in my Go Templ fragment:

```
templ DataGrid(shipmentList []shipments.Shipment, totalItems int, currentPage int, pageSize int) {
	<div
            id="shipments-grid"
            data-replace-url={ "'" + "/envios/lista?page=" + strconv.Itoa(currentPage) + "&pageSize=" + strconv.Itoa(pageSize) + "'" }
        >
```
I didn't realize at first I had to surround the value with "'" because I'm dumb. Thank you so much Ben, I'm starting to fall in love with this project.
