### ISSUE TITLE
Getting started example not working as expected

### ISSUE THREAD

**Issue by samborkent** [starfederation/datastar#23]
Hello, I gave Datastar another try as I really like the vision of the project, but I ran into issues going through the examples. Can you verify that the getting started example is working properly in version v0.12.2?

I have recreated the getting started example as closely and as simply as possible with a Go back-end:

```
package main

import (
	"encoding/binary"
	"encoding/hex"
	"encoding/json"
	"log/slog"
	"math/rand/v2"
	"net/http"
	"strconv"
	"time"
)

type Request struct {
	Input string `json:"input"`
}

var backendData = "initial state"

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "index.html")
	})

	http.HandleFunc("/put", func(w http.ResponseWriter, r *http.Request) {
		var req Request

		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		defer r.Body.Close()

		slog.InfoContext(r.Context(), "Received input.", slog.Int("len", len(req.Input)), slog.String("input", req.Input))

		setHeaders(w)

		backendData = req.Input
		output := `Your input: ` + string(req.Input) + `, is ` + strconv.Itoa(len(req.Input)) + ` long.`
		fragment := `<div id="output">` + output + `</div>`

		sendSSE(w, "", "morph_element", fragment)
	})

	http.HandleFunc("/get", func(w http.ResponseWriter, r *http.Request) {
		setHeaders(w)

		output := `Backend state: ` + backendData
		fragment := `<div id="output2">` + output + `</div>`

		sendSSE(w, "", "morph_element", fragment)

		fragment = `<div id="output3">Check this out!</div>`

		sendSSE(w, "#main", "prepend_element", fragment)
	})

	http.HandleFunc("/feed", func(w http.ResponseWriter, r *http.Request) {
		setHeaders(w)

		ticker := time.NewTicker(time.Second)

		for {
			select {
			case <-r.Context().Done():
				return
			case <-ticker.C:
				buf := make([]byte, 8)
				binary.LittleEndian.PutUint64(buf, rand.Uint64())
				fragment := `<span id="feed">` + hex.EncodeToString(buf) + `</span>`

				sendSSE(w, "", "", fragment)
			}
		}
	})

	http.ListenAndServe(":8000", nil)
}

func setHeaders(w http.ResponseWriter) {
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Connection", "keep-alive")
	w.(http.Flusher).Flush()
}

func sendSSE(w http.ResponseWriter, selector, merge, fragment string) {
	w.Write([]byte("event: datastar-fragment\n"))

	if selector != "" {
		w.Write([]byte("data: selector " + selector + "\n"))
	}

	if merge != "" {
		w.Write([]byte("data: merge " + merge + "\n"))
	}

	w.Write([]byte("data: fragment " + fragment + "\n\n"))
	w.(http.Flusher).Flush()
}
```

This statically loads the following HTML:

```
<!doctype html>
<html>

<head>
    <title>Go + Datastar Example</title>
    <script type="module" defer src="https://cdn.jsdelivr.net/npm/@sudodevnull/datastar@0.12.2"></script>
</head>

<body>
    <h2>Go + Datastar Example</h2>
    <main class="container" id="main">
        <div data-store='{ "input": "", "show": false }'>
            <input type="text" placeholder="Type here!" data-model="input" />
            <div id="output"></div>
            <button data-on-click="$$put('/put')">Send State</button>
            <br />
            <button data-on-click="$$get('/get')">Get Backend State</button>
            <div id="output2"></div>
        </div>
        <br />
        <button data-on-click="$show=!$show">Toggle</button>
        <div data-show="$show">
            <span>Hello From Datastar!</span>
        </div>
        <br />
        <div>
            <span>Feed from server: </span>
            <span id="feed" data-on-load="$$get('/feed')"></span>
        </div>
    </main>
</body>

</html>
```

I encounter the following issues (both on Firefox and Chromium):

- When the feed is enabled, none of the other buttons on the page are working.
- When the feed is disabled the other button do work. However, after clicking any of the two buttons which perform a request to the back-end (Send State and Get Backend State), none of the other buttons on the page will be functional anymore. This also makes it impossible to actually retrieve the backend state stored with the send state request, which the example description suggests should be possible

Can you confirm that this is not expected behaviour?

I feel like the framework can really use tests and Go standard library back-end examples. I would be willing to help with this if possible if I have time.

Thanks in advance!

**Comment by rphumulock** [comment]
I'll take a look.

**Comment by delaneyj** [comment]
So I can confirm there is something up @samborkent around signal effect cleanup being too aggressive, will try to get it fixed tonight.

**Comment by delaneyj** [comment]
@samborkent can you verify, https://data-star.dev/examples/go_hello_sse works for you, if so i can work on a release and a standalone example

**Comment by samborkent** [comment]
@delaneyj Thank you for the quick response.
https://data-star.dev/examples/go_hello_sse the feed now works in conjunction with the buttons. However, the send state button only works once, and the get backend data button only adds the 'Check this out!', but does not retrieve the back-end data.

Tonight I will try to run this new example locally.

**Comment by delaneyj** [comment]
@samborkent  so the getting started guide wasn't written by me.  So I ported it to a doc's example and fixed the underlying issues you were having (hopefully) in v0.12.3.  Check if that works and then I'm make the standalone.

**Comment by samborkent** [comment]
@delaneyj I just checked and the code posted above now works properly in v0.12.3! Thank you so much.
Let me know if I can help with providing Go standard library examples.

**Comment by delaneyj** [comment]
@samborkent glad to help, best place is the htmx discord on the datastar channel.  I know @rphumulock is taking up the mantel of tests and more docs and sure we'd love some help there!
