### ISSUE TITLE
persist example broken

### ISSUE THREAD

**Issue by zangster300** [starfederation/datastar#248]
https://data-star.dev/examples/persist

when entering a value, the value does not persist between page loads (tested on Chrome)

**Comment by bencroker** [comment]
Tracked this down to the store only being updated on SSE events:
https://github.com/starfederation/datastar/blob/a02c0f15a98465b1da24834c8ab9c9842c82fd18/code/ts/library/src/plugins/official/attributes/storage/persist.ts#L32

**Comment by delaneyj** [comment]
Fixed in #296
