### ISSUE TITLE
Issue getting throttling to work on event listeners

### ISSUE THREAD

**Issue by bshankar** [starfederation/datastar#255]
To reproduce add a button with this attribute

`data-on-click.throttle_3s="$get('/')"`
Or
`data-on-click.throttle_1s="$get('/')"`

And press the button many times fast. It sends as many requests as my clicks. No throttling.
I have also tested -

`data-on-click.once="$get('/')"`

It didn't work either. I am using datastar 0.20.1.

**Comment by delaneyj** [comment]
thanks for the report, i'll check it out

**Comment by delaneyj** [comment]
@bshankar wasn't able to repo... please try the new example page https://data-star.dev/examples/debounce_and_throttle and let me know if it works for you.  If not, reopen!

**Comment by bshankar** [comment]
Thanks for the example @delaneyj. It is working. 

But `throttle` and `once` doesn't work in combination with `data-on-click`. `once` also doesn't work with `data-on-raf` (Usually it doesn't make sense to use it that way). 

It is better to use debounce for button clicks. Will use it this way!

**Comment by delaneyj** [comment]
I'm reopening to add a throttle button to check as well, same with once

**Comment by delaneyj** [comment]
Can you give me a specific HTML signs that doesn't work? @bshankar ?

**Comment by bshankar** [comment]
Hi @delaneyj I had to do some digging to reproduce the issue. There's nothing special in the html. I just had:

```html
<div id="login-error"></div>
<button 
    id="login-button" 
    data-on-click.throttle_5s="$post('/login')" 
    data-indicator="_fetching" 
    data-text="$_fetching ? 'Logging in..': 'Login'" 
    data-bind-disabled="$_fetching">
</button>
```

Throttle works with normal http requests like `GET /login` that fetches login.html.
The issue seems to be tied to `POST /login`. So I have attached a sample request.

## Request headers

```
POST /login HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:132.0) Gecko/20100101 Firefox/132.0
Accept: text/event-stream
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Referer: http://localhost:3000/login
Content-Type: application/json
datastar-request: true
Content-Length: 26
Origin: http://localhost:3000
DNT: 1
Sec-GPC: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Priority: u=0
```

## Request body
```json
{ "email": "", "password": ""}
```

## Response headers
```
HTTP/1.1 200 OK
content-type: text/event-stream
cache-control: no-cache
connection: keep-alive
content-length: 158
date: Fri, 29 Nov 2024 03:40:42 GMT
```
## Response

```
event: datastar-merge-fragments
data: fragments <div id="login-error"><span>Incorrect email or password.</span></div>
```

**Comment by delaneyj** [comment]
> The issue seems to be tied to POST /login. So I have attached a sample request.

The post has nothing to do with the throttle.  Try just in the `data-on-click="console.log('foo')"` to verify.  You are trying to change too many variables for us to help see the actual issue currently

**Comment by bshankar** [comment]
I have tried creating a minimal example like updating a counter, `console.log` etc first. They work with throttle. 

Here's a simpler HTML with `data-indicator` removed.

```html
<div id="login-error"></div>
<button 
    id="login-button" 
    data-on-click.throttle_5s="$post('/login')">
</button>
```

I suspect the issue has something to do with `datastar-merge-fragments` event. Is it possible that something changes in the dom or store after the fragment gets merged that resets the throttle timer?

**Comment by bencroker** [comment]
> Is it possible that something changes in the dom or store after the fragment gets merged that resets the throttle timer?

Plugins are reapplied after merging fragments into the DOM. That could be resetting the throttle timer and causing the behaviour described, right @delaneyj?

**Comment by delaneyj** [comment]
Yes the throttle is on the event not on a reapply.  Unstable DOM is going to cause a host of issues if you're trying to do timing stuff on it.

Good catch @bencroker 

You definitely shouldn't be relying on Datastar to stop behavior like this. Putting a rate limiter or handling back pressure on the server is definitely a better choice.  Don't trust the user not to DOS you
