### ISSUE TITLE
Problem with redirects

### ISSUE THREAD

**Issue by Superpat** [starfederation/datastar#27]
So the following events should trigger a redirect without interrupting the stream.

![image](https://github.com/delaneyj/datastar/assets/4533283/db5114ab-cc70-4e19-bcec-4305c63e4e75)

But I never get the redirect, instead the client starts looping the same initial post request to the server.

**Comment by delaneyj** [comment]
I added an example on https://github.com/delaneyj/datastar/tree/issue-27, it seems to be working.  Please pull the branch and try locally.
