### ISSUE TITLE
Support closing SSE connection from client side

### ISSUE THREAD

**Issue by mat02** [starfederation/datastar#276]
From Discord: https://discord.com/channels/1296224603642925098/1296225449260879973/1304096117390180393

In some usecases, it would be good to allow client to close event stream directly (i.e. without explicitly calling some endpoint).

Examples of such usecases:
https://discord.com/channels/1296224603642925098/1296225449260879973/1304037634628386857
https://discord.com/channels/1296224603642925098/1296225449260879973/1311422439871348778

Additional info:
fetchEventSource already exposes AbortController signal.

**Comment by bencroker** [comment]
Thanks for the feature request. Could you please summarise the premise and use-cases, so that we have all of the necessary context here?

**Comment by mat02** [comment]
Currently, stopping an SSE stream often requires a separate backend endpoint to set a flag, which tells the server to end the stream. This adds unnecessary complexity to the backend. Instead of managing stream termination on the server, there could be also option for the client to stop the stream by simply closing the connection. The server will then end the stream automatically.

This approach would be especially useful for simpler applications or as a progressive enhancement for existing ones, where introducing additional coupling between endpoints may not be ideal.

**Comment by bencroker** [comment]
In PHP it is trivial to listen for a closed connection from the client.

```php
if (connection_aborted()) {
    exit();
}
```

Which backend are you using?

**Comment by mat02** [comment]
Yes, it is, but how can we close connection made by datastar? Like, if I have data-on-load="$get('/data')", how can I close this connection using data-on-click somewhere else on the page?

**Comment by bencroker** [comment]
I see, you’d like to do it using an action. Sounds complicated, I’ll let @delaneyj tackle this one!

**Comment by mat02** [comment]
Yes, exactly.
Like, in many cases, when I want to change some parameters of that stream, it seems easier to just close the existing connection and open a new one, with new arguments than control that on the backend, which is also doable, but can cause some additional boilerplate logic.

**Comment by delaneyj** [comment]
If `abortController` was an arg of get/etc would that work for you?

**Comment by magiconair** [comment]
Another dimension is that the server holding the connection might not be the one that gets the termination request. This complicates the server based termination logic.

@delaneyj how about attaching a store variable for the connection that can just be toggled, e.g. `$_streams['/events'] = false`?

**Comment by mat02** [comment]
> If `abortController` was an arg of get/etc would that work for you?

That would work, but following @magiconair, it would be great to just put there a store variable, that defaults to false and close the connection when it changes to true. Not sure, if that's possible?

**Comment by delaneyj** [comment]
The problem is you are trying to make a non-reactive function into a reactive expression.  I think you are putting too much logic into the frontend.  I don't think this is going to work the way you think it is.  We can expose abortController but will that solve your issue?

**Comment by magiconair** [comment]
@delaneyj can you show how one would close the connection on the client with this?

**Comment by delaneyj** [comment]
without writing an actual test i'd think it's something like this in v0.21
```
data-signals-cancel="new AbortController() 
data-on-click="sse('/foo', {abort:cancel.value.abort()"
```
Again that abort hook doesn't exist... but it could

**Comment by mat02** [comment]
Shouldn't this be other way around, that is we pass cancel.value.signal to sse() and then call cancel.value.abort() from some other place on the page?

**Comment by delaneyj** [comment]
One is using a signal to hold an abort signal, you are suggesting using a signal for a non-reactive call.  No, it shouldn't be the other way around.

**Comment by magiconair** [comment]
Hmm, I don't understand what `abort()` does. Which connection does this cancel? Shouldn't this link the connection from the `sse` call to the `AbortController` so that you can cancel it at some later time? Like this...

```html
<div data-signals-cancel="new AbortController()" 
     data-on-load="sse('/events', {abort:cancel.value})">
</div>
<button data-on-click="cancel.value.abort()">Stop</button>
```

`AbortController` also feels a bit abstract. Like an implementation detail leaking out. 

How about this? 

```html
<div data-signals-conn="new SSEController()" 
     data-on-load="sse('/events', {conn:conn.value})">
</div>
<button data-on-click="conn.value.close()">Stop</button>
```

**Comment by delaneyj** [comment]
This is a native part of the browser @magiconair https://developer.mozilla.org/en-US/docs/Web/API/AbortController

**Comment by mat02** [comment]
> ```
> data-signals-cancel="new AbortController() 
> data-on-click="sse('/foo', {abort:cancel.value.abort()"
> ```

@delaneyj I'm confused. In your example, wouldn't ```cancel.value.abort()``` be called even before sse (that is, when it's return value, which is undefined btw, is assigned to abort property of the object passed to sse function)? 

When AbortController is used with fetch, we pass the signal to the fetch function and then invoke cancelation thorugh abort() call, often in on-click handler. I thought this would work the same in D*, i.e. we pass some "flag" to sse() and control it externally, so when abort() is called, that sse() call is cancelled.

I may be missing some context, as I'm not yet familiar with the inner workings of D* ;)

**Comment by delaneyj** [comment]
Yeah sorry, you wouldn't call abort there but with another event

**Comment by mat02** [comment]
Ok, then I'm perfectly fine with such solution :)
On the other hand, @magiconair I would rather not wrap Abort Controller in some additional D*-specific abstraction.

**Comment by magiconair** [comment]
I didn't know that `AbortController` is part of the WebAPI. I still don't understand where the `AbortSignal` is connected to the `fetch` request. Should the example read like this?

```
data-signals-cancel="new AbortController()"
data-on-click="sse('/foo', {abort:cancel.value}">
```

Is `value` then evaluated to the `signal` property of the controller or the controller itself? Should this be like this?

```
data-signals-cancel="new AbortController()"
data-on-click="sse('/foo', {abort:cancel.signal.value}">
```

Because in order to call `abort()` we'd have to call `cancel.value.abort()`, right?

```
data-on-click="cancel.value.abort()"
```

**Comment by nonnorm** [comment]
I think it would end up looking like this:
```
data-signals-cancel="new AbortController()"
data-on-click="sse('/foo', {abort:cancel.value.signal}"
```
And then on some other element:
```
data-on-click="cancel.value.abort()"
```

**Comment by delaneyj** [comment]
Yes that looks right

**Comment by magiconair** [comment]
That’s what I meant 😄 duh. Great. Thank you

**Comment by delaneyj** [comment]
Cool I'll add this

**Comment by scotthaleen** [comment]
I couldn't find any examples of how to use `abort` and I spent a significant amount of time trying to figure out how to use this before I finally got it to work. 

Here is an example of how I got it working for anyone else trying to figure this out
I _think_ this is the correct usage

```html
<div data-signals-btndisabled="false">
  <div data-signals-_cancel="null">
    <div>Stream</div>
      <button
        data-on-click="$_cancel=new AbortController();$btndisabled = true;@get('/stream', {abort: $_cancel.signal})"
        data-attr-disabled="$btndisabled">start</button>
      <button
        data-on-click="$_cancel.abort(); $btndisabled = false;"
        data-attr-disabled="!$btndisabled">stop</button>
    </div>
    <div id="stream-content"></div>
</div>
```

Also the `_` (underscore) was required as described by 

https://data-star.dev/reference/action_plugins#options
> includeLocal - Whether to include local signals (those beggining with an underscore) in the request. Defaults to false.

without the underscore I was getting an error on the backend when receiving the request.

**Comment by bencroker** [comment]
> without the underscore I was getting an error on the backend when receiving the request.

@scotthaleen what was the error?

**Comment by scotthaleen** [comment]
> > without the underscore I was getting an error on the backend when receiving the request.
> 
> [@scotthaleen](https://github.com/scotthaleen) what was the error?

well now I can't reproduce the server error.  Maybe that `_` was unrelated.  A lot of the hangup was, I was trying to use the `data-signals` _object_ syntax 

`data-signals="{btndisabled: false, cancel: new AbortController()}"`

When I defined it this way and tried to use it

```
data-on-click="$btndisabled = true;@get('/stream', {abort: $cancel.signal})"
```
I would get errors about it not being defined. 

```﻿
errors.ts:13 Uncaught datastar runtime error: ExecuteExpression
More info: https://data-star.dev/errors/runtime/execute_expression?metadata=%7B%22plugin%22%3A%7B%22name%22%3A%22on%22%2C%22type%22%3A%22Attribute%22%7D%2C%22element%22%3A%7B%22id%22%3A%22datastarvfac4i%22%2C%22tag%22%3A%22BUTTON%22%7D%2C%22expression%22%3A%7B%22rawKey%22%3A%22onClick%22%2C%22key%22%3A%22click%22%2C%22value%22%3A%22%24btndisabled+%3D+true%3B%40get%28%27%2Fstream%27%2C+%7Babort%3A+%24cancel.signal%7D%29%22%2C%22validSignals%22%3A%5B%22btndisabled%22%5D%2C%22fnContent%22%3A%22return+%28%28%29+%3D%3E+%7B%5Cnctx.signals.signal%28%27btndisabled%27%29.value+%3D+true%3B%5Cnreturn+%28ctx.actions.get.fn%28ctx%2C%27%2Fstream%27%2C+%7Babort%3A+%24cancel.signal%7D%29%29%3B%5Cn%7D%29%28%29%22%7D%2C%22error%22%3A%22%24cancel+is+not+defined%22%7D
Context: {
  "plugin": {
    "name": "on",
    "type": "Attribute"
  },
  "element": {
    "id": "datastarvfac4i",
    "tag": "BUTTON"
  },
  "expression": {
    "rawKey": "onClick",
    "key": "click",
    "value": "$btndisabled = true;@get('/stream', {abort: $cancel.signal})",
    "validSignals": [
      "btndisabled"
    ],
    "fnContent": "return (() => {\nctx.signals.signal('btndisabled').value = true;\nreturn (ctx.actions.get.fn(ctx,'/stream', {abort: $cancel.signal}));\n})()"
  },
  "error": "$cancel is not defined"
}
    at $e (https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-beta.11/bundles/datastar.js:2:2403)
    at P (https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-beta.11/bundles/datastar.js:4:437)
    at Pn.P.error (https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-beta.11/bundles/datastar.js:7:109)
    at HTMLButtonElement.s (https://cdn.jsdelivr.net/gh/starfederation/datastar@v1.0.0-beta.11/bundles/datastar.js:12:7948)
$e @ errors.ts:13
P @ errors.ts:56
Pn.P.error @ engine.ts:363
s @ on.ts:33

```


Switching to `data-signals-cancel="new AbortController()"` resolves this. 


I assume `data-signals={btndisabled: false, cancel: new AbortController()}` is problematic because `cancel` has children `abort` and `signal` 


I later realized it just didn't make sense to instantiate the AbortController globally since I need a new instance per start/stop anyway. So I was just starting with `cancel: null` and doing

```
data-on-click="$cancel = new AbortController();@get('/stream', {abort: $cancel.signal})"
```
which also works



---

Here is the snippet that reproduces error `$cancel is not defined` error

```html
	<div 
	data-signals="{cancel: new AbortController()}"
	>
		<button
			data-on-click="$btndisabled = true;@get('/stream', {abort: $cancel.signal})"
			data-attr-disabled="$btndisabled"

			>connect</button>
```
