### ISSUE TITLE
Figure out forms

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#293]
Figure out working with forms in Datastar (aka Delboy’s Magnum Opus).

For reference: https://github.com/starfederation/datastar/discussions/82, https://github.com/starfederation/datastar/discussions/136

**Comment by bencroker** [comment]
For reference: https://github.com/starfederation/datastar/discussions/82, https://github.com/starfederation/datastar/discussions/136

**Comment by Superpat** [comment]
First of all, do we want to figure out forms before v1.0 ? 

Second of all, how much magic do we want ?

- Should the name attribute become the name of a signal ? 
- Should it be a nested signal under the form's namespace  ? 
- Should the native browser validation be run on inputs before their value is propagated to their bound signal ?
- Should changes to a signal be propagated to it's bound input if the value does not pass that input's validation ?

I'm sure there's other stuff, but that's the questions I had.

**Comment by dkotik** [comment]
> First of all, do we want to figure out forms before v1.0?

Absolutely!

> Should it be a nested signal under the form's namespace?

Certainly!

I wondered if there is an ability to scope $post body here: https://github.com/starfederation/datastar/discussions/302 I think this issue is entirely related. Right now there is too much magic. JSON encoding a step away from hypermedia. Should it perhaps be an extension, with form data being the default? Seem sensible to me.

Also, using `<input>` and such without `<form>` tag is technically incorrectly formed HTML - it gets picked on by linters. I suggest that data submission should be handled via forms, not the global store of everything.

**Comment by Superpat** [comment]
> > First of all, do we want to figure out forms before v1.0?
> 
> Absolutely!

I ask the question because it could very well be a separate plugin that does not affect the datastar core, so released on a separate occasion. Though stuff like validation of data-bind would occasion changes to other plugins.


> I wondered if there is an ability to scope $post body here: #302 I think this issue is entirely related. Right now there is too much magic. JSON encoding a step away from hypermedia. Should it perhaps be an extension, with form data being the default? Seem sensible to me.
> 
> Also, using `<input>` and such without `<form>` tag is technically incorrectly formed HTML - it gets picked on by linters. I suggest that data submission should be handled via forms, not the global store of everything.

I highly doubt @delaneyj is going to want to change the default format of post requests data in datastar, but the ability to use a different encoding for the data could be very useful. I know I've had a datastar project that used an external api that only accepted  formdata encoded images and having to reparse the file as formdata was annoying.

**Comment by bencroker** [comment]
> First of all, do we want to figure out forms before v1.0?

Yes, that’s the plan.

> Second of all, how much magic do we want?

None. Or as little as possible.

> Should the name attribute become the name of a signal?
> Should it be a nested signal under the form's namespace?

This is conflating signals with forms.

> Should the native browser validation be run on inputs before their value is propagated to their bound signal?
> Should changes to a signal be propagated to it's bound input if the value does not pass that input's validation?

This could be an interesting feature (`data-validate`, perhaps), but is unrelated to solving forms.

---

Our current thinking is that we add a “form mode” option to the `sse()` action that changes its behaviour to look for the closest `form` element (or temporarily create one if none exists), add prevent default, perform validation checks and multipart encode it. In this mode, only form elements within the `form` are sent to the backend, no signals are sent.

**Comment by oluatte** [comment]
Would also love this. Just hit the forms questions today.

**Comment by dkotik** [comment]
> Our current thinking is that we add a “form mode” option to the `sse()` action that changes its behaviour to look for the closest `form` element (or temporarily create one if none exists), add prevent default, perform validation checks and multipart encode it. In this mode, only form elements within the `form` are sent to the backend, no signals are sent.

this sounds spot on for first stab iteration!

**Comment by bencroker** [comment]
> this sounds spot on for first stab iteration!

@dkotik anything missing? The idea is that this is the _only_ iteration.

@Superpat any thoughts from your side?

**Comment by Superpat** [comment]
That would retain compatibility with form validation in stuff like laravel request validation, so I'm happy with it.

**Comment by dkotik** [comment]
> @dkotik anything missing? The idea is that this is the _only_ iteration.

The library is more likely to suceed, if you do not rush with iterations. Here is one issue that boiled me over in Svelte that they really messed me up in 4.0: there was no wrap/override mechanism for their injected fetch, so I couldn't inject all requests with authorization token. They have fixed it since, but I couldn't believe that there was such a blunder for so long - and I found Github issues complaining about it that were ignored for years.

So, consider exposing access to fetch somehow? May be create a signal with request object. This is what comes to mind at the moment. I will keep thinking.

**Comment by bencroker** [comment]
> So, consider exposing access to fetch somehow?

We expose [options](https://data-star.dev/reference/action_plugins#options) on the `sse()` action, if that’s what you mean? Those options can be extended at any point in future, but I don’t see us ever exposing the `fetch` function directly. If you need that custom then you probably want a custom plugin.

**Comment by dkotik** [comment]
Oh! Error handling! I simply read the text of the response as error message when !response.ok - I think that is a great default behavior. May be have a hook for somebody to parse out JSON if they expect a list of errors instead of one error. Here is the code I used:

```javascript
export async function postForm(target, data, token) {
  return fetch(target, {
    method: "POST",
    headers: {
      Authorization: "Bearer " + token,
      "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
    },
    body: Object.keys(data)
      .map((key) => {
        return encodeURIComponent(key) + "=" + encodeURIComponent(data[key]);
      })
      .join("&"),
  })
    .catch((networkError) => {
      console.log("network error:", networkError);
      throw new Error("disconnected from the server");
    })
    .then(async (res) => {
      // here <-----
      if (!res.ok) throw new Error(await res.text());
      return res;
    });
}

window.postForm = postForm;
```

**Comment by bencroker** [comment]
You must not have read https://data-star.dev/essays/i_am_a_teapot
I’m not sure @delaneyj will budge on this.

**Comment by Superpat** [comment]
Should we add the ability to target a specific form, like the form attribute does ?

**Comment by bencroker** [comment]
That’s something I previously considered, will add to the PR.

**Comment by dkotik** [comment]
> You must not have read https://data-star.dev/essays/i_am_a_teapot I’m not sure @delaneyj will budge on this.

So iconoclastic! I love it! I can think of some exceptions though: failing byte range request, throttled page, unauthorized access, expired content, absent CSRF token, TLS error... Also, there are plenty of hot takes against using redirects from coding veterans. I view the above linked as dropping error value in Golang. If something can fail, and an HTTP load can fail a million different ways, there should be sensitivity to that possibility, at least as a customizable option.

**Comment by delaneyj** [comment]
> failing byte range request, throttled page, unauthorized access, expired content, absent CSRF token, TLS error.

When you are doing SSE via Datastar all of these are moot.  You are complecting external errors to internal errors.  Absent CSRF is a dev error, expired content doesn't apply to SSE.  All these issues you are close to ***are*** backend choices.  The page either updates with new content or redirects to a new page.

**Comment by dkotik** [comment]
@delaneyj, CSRF can be expired, auth header token can be expired. SSE connection itself can fail. Also, a form submission must not necessarily create an SSE connection. There is likely that there is already a GET sse running somewhere on the page.

I see that you expect the dev to stream HTML fragments with error messages in them. Logical. However, that fetch request should still throw an error into console and be interceptible with .catch, in case the dev wants to have a custom handler for things like "my wifi just died." It is important for things like internationalization and accessibility as well.

**Comment by Superpat** [comment]
In datastar there are only sse connections. You dont have to keep it alive, you can shut it down with zero response, but it's always sse. Also I feel like any auth error should cause a redirect anyways. SSE is a self reconnecting standard.  

I'm curious why it's important for internationalization / accessibility ?

**Comment by dkotik** [comment]
@Superpat visually impaired users that use a screen reader may not be aware that they lost connection as their device doesn't immediately announce it - can be as long as 30 seconds of retries.

There should be a hook to pop up something on the client side like "trying to reconnect..." Also, not everybody reads English, so it is imperative to be able to override that message or any failure state with a locale-sensitive response.

**Comment by delaneyj** [comment]
> @delaneyj, CSRF can be expired, auth header token can be expired. SSE connection itself can fail. Also, a form submission must not necessarily create an SSE connection. There is likely that there is already a GET sse running somewhere on the page.
> 
> I see that you expect the dev to stream HTML fragments with error messages in them. Logical. However, that fetch request should still throw an error into console and be interceptible with .catch, in case the dev wants to have a custom handler for things like "my wifi just died." It is important for things like internationalization and accessibility as well.

I think you are missing the point of the essay.  Everything you're talking about is orthogonal to the state of the SSE connection.

**Comment by dkotik** [comment]
@delaneyj I get the essay. I am conversing with it, because I was asked to opine.

**Comment by bencroker** [comment]
Bringing this back to forms, here’s where we are: https://github.com/starfederation/datastar/pull/400
Unless there are any final things to note, I think this is loaf is baked.

**Comment by bencroker** [comment]
Completed in https://github.com/starfederation/datastar/pull/400.
