### ISSUE TITLE
data-text Parsing Issue with appended methods

### ISSUE THREAD

**Issue by SpiralOSS** [starfederation/datastar#30]
Was working through the documentation and got hung up on this:
`<label data-text="$input.toUpperCase()"></label>`

which results in this anonymous function:
```
try {
  return ctx.store().input.toUpperCase.value()
} catch (e) {
  throw e  // TypeError: undefined is not an object (evaluating 'ctx.store().input.toUpperCase.value')
}
```

I messed with it and found it works properly if you add a space before the dot:
`<label data-text="$input .toUpperCase()"></label>`

I saw this example and this works:
`<label data-text="$input + 'extra'"></label>`

Thanks, this is the first library that feels approachable to a web-noob.

**Comment by delaneyj** [comment]
Sorry for the late response, this should work, will test and verify today

**Comment by delaneyj** [comment]
Can confirm the issue, surprised others haven't run into it.  The core issue is Datastar support nested signals in the store.  So it thinks you are trying to access `input.toUppercase` as a signal.  Working on a fix now.
