### ISSUE TITLE
Go SDK: Improve compatibility with Fiber web framework

### ISSUE THREAD

**Issue by freefalling** [starfederation/datastar#300]
While implementing SSE with DataStar Go SDK in a Fiber application, I encountered challenges due to the SDK's dependency on net/http interfaces.

- DataStar's NewSSE requires http.ResponseWriter and http.Request
- Fiber uses fasthttp underneath
- Attempts to bridge using Fiber's HTTP adapter result in non-functional SSE connections

Working alternative without using DataStar GO SDK helpers:

```
app.Get("/events", func(c *fiber.Ctx) error {
    c.Set("Content-Type", "text/event-stream")
    c.Set("Cache-Control", "no-cache")
    c.Set("Connection", "keep-alive")
    c.Set("Transfer-Encoding", "chunked")

    c.Status(fiber.StatusOK).Context().SetBodyStreamWriter(func(w *bufio.Writer) {
        for {
            msg := fmt.Sprintf("event: datastar-merge-signals\nretry: 1000\ndata: signals { \"ordersToday\": %s }\n\n", 
                strconv.Itoa(rand.Intn(100)))
            fmt.Fprintf(w, msg)
            
            if err := w.Flush(); err != nil {
                return
            }
            time.Sleep(2 * time.Second)
        }
    })
    return nil
})
```
Is there a viable way that maybe I'm not seeing at the moment to use your SDK along side with Fiber without workarounds?

**Comment by delaneyj** [comment]
I will never support fasthttp in the Go SDK.  You are welcome to make a separate SDK.  It's wrong and doesn't even support HTTP2.

**Comment by freefalling** [comment]
I understand the reasons behind your statement. I was struggling on why my handler was stuck in the event loop until I analyzed the SDK source code. No problem, now I know that the custom methods I developed were needed for my case. Good point on HTTP2, I wasn't are of that. Thank you again @delaneyj.
