### ISSUE TITLE
Feature Request: Putting numbers in the store from input tag

### ISSUE THREAD

**Issue by bshankar** [starfederation/datastar#304]
Say I have an input of type number:

```
<input type="number" data-model="count" />
```
When I type 120 in this input, it's a string  in the store instead of being a number.
 `{ phone: "120" }`
 
 Can we do this conversion automatically inside datastar?

**Comment by bshankar** [comment]
This is a limitation of HTML. We have to get a reference to the element and then use `inputElement.value.valueAsNumber`.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/valueAsNumber

**Comment by bencroker** [comment]
Exactly!

**Comment by bshankar** [comment]
Hi @bencroker Sorry I wasn't clear. I was making a feature request to do this conversion automatically inside datastar. It is pretty common. So it would benefit users who don't want to parse on the backend or use custom js.

**Comment by bencroker** [comment]
Oh I see, reopening for consideration.

**Comment by delaneyj** [comment]
I don't think this is accurate, i'm alread doing the conversion for you.  Need a reproduceable example... It should be fine in at least v0.20+

**Comment by bshankar** [comment]
@delaneyj Here's an example HTML of printing out the type of `counter` from a number input. I have also reproduced it with locally downloaded bundle of version 0.20.1.

```html
<html>
<head>
  <script type="module" src="https://cdn.jsdelivr.net/gh/starfederation/datastar/bundles/datastar.js"></script>
</head>

<body>
  <input type="number" data-model="counter" />
  <button data-on-click="console.log(typeof $counter)">Click me</button>
</body>
</html>

```
Video
[Kooha-2024-12-08-08-50-19.webm](https://github.com/user-attachments/assets/58356958-62d0-42c8-a212-97b96dea2b92)

**Comment by delaneyj** [comment]
Seems to work fine in latest, v0.21.0 https://codepen.io/datastar-ceo/pen/EaYKQvY  If you run into more issue please let us know on Discord #help first
