### ISSUE TITLE
Consider `datastar-replace-url` event

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#31]
The `replaceUrl` attribute plugin exists for keeping the URL in sync with signals, but it might be overkill. If we were to say that only the backend should be allowed to replace the URL, then a new SSE event might be a better way to make this possible.

Before:

```html
<div data-replace-url="'/page' + $page">
```

After:

```
event: datastar-replace-url
data: url /page2
```

**Comment by Superpat** [comment]
I like this better then the action or attribute

**Comment by bencroker** [comment]
Superceded by https://github.com/starfederation/datastar/pull/37
