### ISSUE TITLE
Allow focusing at the end of a fragment

### ISSUE THREAD

**Issue by Superpat** [starfederation/datastar#33]
When elements inserted / morphed into the dom are bigger than the screen, data-focus will focus on the center of the element. In some cases this is undesired. data-focus.end="" would allow us to force the focus to show the end of the element instead.

**Comment by delaneyj** [comment]
Can't find that option in https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus.  How are you handling it now?

**Comment by delaneyj** [comment]
try out [issues-33 ](https://github.com/delaneyj/datastar/tree/issue-33) branch and see if the `/examples/scroll_into_view` example matches your needs
