### ISSUE TITLE
"TODO" is rendered in the website

### ISSUE THREAD

**Issue by jmcudd** [starfederation/datastar#332]
I was reading the guide and this doesn't make any sense to me, it seems incomplete. Was the intent to include it in the rendered docs?

https://github.com/starfederation/datastar/blob/2fe3713f39514d8ef108317251b56ed9c38a1dcb/site/static/md/guide/go_deeper.md?plain=1#L119-L130

![screenshot_20241209-112515](https://github.com/user-attachments/assets/fefcc1c3-501c-4d84-93d3-8d4f48e6b58a)

**Comment by delaneyj** [comment]
Sorry, my fault!

**Comment by bencroker** [comment]
Thanks for reporting this, @jmcudd. I removed my TODO and fixed up the syntax. This page really needs a rewrite, I just need to ponder what approach to take.
https://data-star.dev/guide/go_deeper
