### ISSUE TITLE
Bundler bug

### ISSUE THREAD

**Issue by bencroker** [starfederation/datastar#339]
Last I checked the bundler was outputting an invalid bundle. Got an error about `ServerSentEvents as SSE` when using the JS bundle.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Changed the import of ServerSentEvents from a named import with alias to a default import to resolve bundling issues.

You can review changes in this commit: https://github.com/mnmnk43434/starfederation-datastar-339/commit/644e8abcebac5359dd3c57b8d90c52adfb0102d1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
