### ISSUE TITLE
Some demos not working on the site

### ISSUE THREAD

**Issue by sebastianpetrovski** [starfederation/datastar#352]
Hey,

Recently came across datastar, it looks super cool and seems like a fun way to build for the web.

I noticed some of the demos on the site aren't working for me on desktop (windows 11, chrome) or mobile (android, chrome). 

https://data-star.dev/guide/getting_started#setall

https://data-star.dev/guide/getting_started#toggleall

https://data-star.dev/examples/scroll_into_view

P.S. very nice: 

![image](https://github.com/user-attachments/assets/2fe2807d-8766-4042-8e1b-32e5e2a214ab)

**Comment by bencroker** [comment]
Thanks for reporting this! `setAll()` and `toggleAll()` have been fixed.

I’m seeing this error at https://data-star.dev/examples/scroll_into_view
> Uncaught error scrollIntoViewKeyNotAllowed

@delaneyj it looks like the modifiers in `data-scroll-into-view__instant__vstart__hcenter` are being considered part of the key.

**Comment by bencroker** [comment]
This turned out to be an issue with the example, fixed in https://github.com/starfederation/datastar/commit/436e4ddbd818cf18034def47d37e9142c1de5b1e.
