### ISSUE TITLE
Add ID of triggering element to request

### ISSUE THREAD

**Issue by magiconair** [starfederation/datastar#356]
If you have multiple instances of the same component on a page they should have different IDs if you want to use the default Datastar merging behavior.

Then the generated fragment needs to render the correct ID. HTMX has the `HX-Trigger` header which contains the `id` of the element which triggered the request - if the `id` exists. (https://htmx.org/reference/#request_headers)

Having a `Datastar-Trigger` header or `DS-Trigger` header would be helpful. The workaround is to duplicate the ID in a query parameter which is error prone. 

Not sure whether to vote for shorter headers (`DS-Trigger`) or more consistent headers (`Datastar-Trigger`)

```html
<h1>Machine 123</h1>
<div id="stats-123" data-on-load="sse('/widget/stats/machine?machineId=123')"></div>
<div id="yield-123" data-on-load="sse('/widget/yield/machine?machineId=123')"></div>
<div id="status-123" data-on-load="sse('/widget/status/machine?machineId=123')"></div>

<h1>Machine 456</h1>
<div id="stats-456" data-on-load="sse('/widget/stats/machine?machineId=456')"></div>
<div id="yield-456" data-on-load="sse('/widget/yield/machine?machineId=456')"></div>
<div id="status-456" data-on-load="sse('/widget/status/machine?machineId=456')"></div>
```

**Comment by bencroker** [comment]
Maybe I’m missing something, but your backend should have everything it needs in `/widget/stats/machine?machineId=123` to create a fragment to replace an element with ID `stats-123`. As discussed ad nauseam in Discord, your backend should drive your frontend. If the backend needs to know some state, send it via signals (or query string params). What am I missing?

**Comment by magiconair** [comment]
@bencroker how does the backend know that the id is `stats-123` without me providing it,  hardcoding it in the response or assuming that the id must follow a certain pattern for this use case, e.g. `stats-<machineID>`. 

If I hardcode it in the response then all widget instances must have the same id on all pages. 

If I assume a certain pattern then both page and widget authors (i.e. different teams) have to know about this and agree on the algorithm to create the matching id. 

If I have to tell it then in 0.21 D* I have to include the id into the URL as a query parameter or in the path which means I have to duplicate it. This is a source for subtle errors which are hard to spot. 

```
<div id="abc" data-on-load="sse('/widget?id=abc')"></div>
         ^^^                                ^^^
```

What I'm suggesting is that D* provides the value of the `id` field in a header so that the backend can keep track of it if it needs to without the page author having to duplicate that value or choosing one of the other methods.

**Comment by bencroker** [comment]
You’re making this all about your problem, rather than a general problem. To keep it relevant to Datastar, we need to discuss whether this makes sense to add as a generally available feature.

Right now, what I’m hearing is that you want to be able to do something like this:

```html
<div id="a" data-on-load="sse('/widget')"></div>
<div id="b" data-on-load="sse('/widget')"></div>
<div id="c" data-on-load="sse('/widget')"></div>
```

Without the backend having to know about the IDs `a`, `b` or `c`. For the backend to drive the frontend, it _must_ have _some_ context, which you can provide via signals, a query string parameter, or implied context (hardcoding).

Using signals:

```html
<div id="a" data-signals-widget-a="1" data-on-load="sse('/widget')"></div>
<div id="b" data-signals-widget-b="1" data-on-load="sse('/widget')"></div>
<div id="c" data-signals-widget-c="1" data-on-load="sse('/widget')"></div>
```

Using query string parameters:

```html
<div id="a" data-on-load="sse('/widget?id=a')"></div>
<div id="b" data-on-load="sse('/widget?id=b')"></div>
<div id="c" data-on-load="sse('/widget?id=c')"></div>
```

Using implied context, in which you target a class instead of an ID: 

```html
<div id="a" class="widget" data-on-load="sse('/widget')"></div>
<div id="b" class="widget" data-on-load="sse('/widget')"></div>
<div id="c" class="widget" data-on-load="sse('/widget')"></div>
```

and your SSE event will look like this:

```
event: datastar-merge-fragments
data: selector .widget
data: mergeMode inner
data: fragments ...
```

There may still be a case to be made for passing the element ID along with the the SSE request. I just want to be sure that we’re approaching this in a hypermedia-first approach, and not falling into the SPA trap.

**Comment by magiconair** [comment]
The problem is how to simplify the generation of the correct HTML when the same fragment is embedded on multiple pages with different element ids AND the updates are delivered via a separate connection. I think that's missing in my original problem description.

```html
// page1.html
<!-- 
The initial update for 'a' is delivered via the initial
sse('/widget') call which is then closed immediately.

All future updates for 'a' are delivered via /events 
which needs to receive a <div id="a">...</div> response.
-->
<div data-on-load="sse('/events')></div>
<div id="a" data-on-load="sse('/widget')"></div>
```

```html
// page2.html
<!-- /events receives <div id="x">...</div> fragments. -->
<div data-on-load="sse('/events')></div>
<div id="x" data-on-load="sse('/widget')"></div>
```

This can be sovled by adding the element id as a query parameter like below but it requires the developer to remember this and Datastar already has this information so it could embed it into the initial `sse('/widget')` request header. Also, in practice the element ids and URLs will be longer as in these examples and it is less obvious that this information has to be duplicated in a query parameter for example. Furthermore, different widget authors might choose different query parameter names which may make this more difficult.

```html
<div data-on-load="sse('/events')></div>
<div id="x" data-on-load="sse('/widget?id=x')"></div>
<div id="y" data-on-load="sse('/widget2?selector=#y')"></div>
```

## Why is this a problem/Why deliver future updates via a different connection?

We will have pages with more than 6 widgets on them and with HTTP/1.1 the number of connections to a host is generally limited to 6 connections. One assumption is that I cannot guarantee an HTTP/2 connection to my site in every situation and that's why I have to coalesce all future updates through a single separate connection.

There might be other reasons for coalescing the updates through a separate connection. I want to avoid that a user only gets partial updates for a crucial dashboard. I need to think about that. But that might also be the flaw in my reasoning. 

Using the `mergeMode: inner` approach works if the updates don't need to be coalesced. Without that you’d have to provide a unique `selector`. 

Not everyone will need this but having that ability/information is useful in the described situation IMHO. Similar to how the `Datastar-Request: true` header is sometimes useful.

## Current status

I have this working with the element id as a query parameter and I need to think about need to coalesce the updates through a separate connection. Switching to HTTP/2 might be the simpler/right solution since then no separate connection is required and the `mergeMode: inner` approach would work. 

This might be slightly more complex in the local development environment where I deliberately run multiple HTTP servers behind a reverse proxy. HTTP/2 generally requires TLS and Caddy which provides automatic TLS on localhost does not flush SSE connections properly. (https://github.com/caddyserver/caddy/issues/6293) which is why I've switched to `nginx` which doesn't enable HTTP/2 by default and also does not provide TLS by default.

That's the best explanation I can give at the moment.

**Comment by delaneyj** [comment]
Per our many discussions I still think you'd do best to implement an event bus like NATS and have a single GET.

**Comment by magiconair** [comment]
That’s what I have right now. Since /widget and /events are on different servers I need to keep track of which widget is on which page to find the right connection. 

Either each widget keeps track and publishes one change per connection or each event stream listens for all widget updates on the page. Or I’d have a separate component to do this. I can’t think of a clever NATS subject setup since this is an MxN problem. 

In the first case the /widget implementation becomes more complex because of the bookkeeping in the second case the /events implementation. 

Right now I’ve moved the complexity into the /events handler since this seems more generic and each widget has to publish exactly one update.

**Comment by bencroker** [comment]
> Using the `mergeMode: inner` approach works if the updates don't need to be coalesced. Without that you’d have to provide a unique `selector`.

Have you considered that a selector can target multiple elements using a class? I gave this example above:

```html
<div id="a" class="widgetA" data-on-load="sse('/widget')"></div>
```

```
event: datastar-merge-fragments
data: selector .widgetA
data: mergeMode inner
data: fragments ...
```

**Comment by magiconair** [comment]
I have considered that but after some more conversations with colleagues I think you guys are right after all. 

The whole problem stems from me wanting to render the HTML on the backend and deliver that to the frontend. Delaney told me early on to use the page to setup the store and wire up the signals to some web components. 

I'll try something like this once I can think straight again.

```html
<div data-signals="{
  widgets:{
    widget1:{count:0},
    widget2:{count:0}
  }
}" data-on-load="sse('/events')"></div>

<my-counter data-attributes-count="widgets.widget1.count.value" name="widget1"></my-counter>
<my-counter data-attributes-count="widgets.widget2.count.value" name="widget2"></my-counter>
```

So please hold off on this and thanks for your patience.

**Comment by bencroker** [comment]
Great, let us know what you end up with!

**Comment by magiconair** [comment]
OK, so here is what I ended up doing. Built the counter as lit components independent of D*, component fires an event when the button is clicked (simulates a data update), each page has a unique ID in the D* store to identify a specific connection, a NATS broker in the background which distributes state updates to the correct page, and the markup on the page looks like this. No IDs, all wiring done on the page. 

```html
<div data-on-load="sse('/events')" data-signals="{counter1: 0, counter2: 0}"></div>
<div class="d-flex">
    <nv-counter
        name="counter1"
        data-attributes-updates="counter1.value"
        data-on-load="sse('/widgets/counter/counter1')"
        data-on-count="sse('/widgets/counter/counter1/count')"
    ></nv-counter>
    <nv-counter
        name="counter2"
        data-attributes-updates="counter2.value"
        data-on-load="sse('/widgets/counter/counter2')"
        data-on-count="sse('/widgets/counter/counter2/count')"
    ></nv-counter>
</div>
```

```typescript
import { LitElement, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';

@customElement('nv-counter')
export class NVCounter extends LitElement {
    @property({ type: String }) name = '';
    @property({ type: Number }) updates = 0;

    createRenderRoot() {
        return this; // do not use the shadow DOM
    }

    render() {
        return html`
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">${this.name}</h5>
                    <h6>Updates: ${this.updates}</h6>
                    <button @click="${this._count}" class="btn btn-primary">Count</button>
                </div>
            </div>
        `;
    }

    private _count() {
        this.dispatchEvent(new CustomEvent('count'));
    }
}
```

![image](https://github.com/user-attachments/assets/2ef879e6-7d4f-4fa9-bf85-ad5ed9a6410e)

Again, thanks for your patience!

**Comment by delaneyj** [comment]
This is the way. State in the right place
