### ISSUE TITLE
Bundler appears broken

### ISSUE THREAD

**Issue by jmcudd** [starfederation/datastar#375]
The bundler (https://data-star.dev/bundler) on the website appears broken. No errors found in the console.
![2024-12-13_22-30 13](https://github.com/user-attachments/assets/12ad49ea-ba7a-4b99-b4f4-ed3c26c4475e)

**Comment by bencroker** [comment]
Confirmed, please investigate, @delaneyj.

**Comment by bencroker** [comment]
This has been fixed!
