### ISSUE TITLE
Inner Merge stripping outer html tags

### ISSUE THREAD

**Issue by ITarrant** [starfederation/datastar#377]
When using Inner merge mode, the swapped in html becomes the contents of the sse string minus the outer html tags.

First example  
```<div id="greeting">Hello</div>``` and using inner merge selecting #greeting with 
```<span class="bold">World</span>``` results in ```<div id="greeting">World</div>```

Second example
```<div id="greeting">Hello</div>``` and using inner merge selecting #greeting with 
```<div class="row"><div class="col">Good</div><div class="col">Sir!</div></div>```
results in ```<div id="greeting"><div class="col">Good</div><div class="col">Sir!</div></div>```

Third example
```<div id="greeting">Hello</div>``` and using inner merge mode selecting #greeting with ```World``` results in no action taking place

**Comment by bencroker** [comment]
Have you tried an outer merge?

**Comment by ITarrant** [comment]
wouldn't outer merge just replace the entire div being selected, instead of inserting new content within it?

**Comment by bencroker** [comment]
It should select the outer element of the content you want to merge.
