### ISSUE TITLE
TC39 signals proposal

### ISSUE THREAD

**Issue by pepe** [starfederation/datastar#381]
When reading #356, I came across the lit library, and on its page, I found a reference to this proposal: https://github.com/tc39/proposal-signals. I tried to search the issues but have not found any traces. So, I would like to ask you if you are aware of this, as I think it is relevant for Datastar.

**Comment by delaneyj** [comment]
Very aware, nothing actionable for now.  For the kind of question the Discord is your best bet most of the time.

**Comment by pepe** [comment]
I am sorry. This could have been evident from the number of issues.

**Comment by delaneyj** [comment]
No worries, thanks for looking out.  Unless they support nested signals not much in Datastar will change from the outside.  If anything, I'll be able to delete code and make it even smaller.  Welcome!
