### ISSUE TITLE
Support infinite retries, make initial retry time configurable

### ISSUE THREAD

**Issue by magiconair** [starfederation/datastar#382]
For some use cases I would need an indefinite retry since otherwise we would have to reload the page to re-establish the connection. As a followup to #190 I would like to suggest the following additions:

* Document that the initial retry wait time is `1s`
* Provide an `retryInitialWaitMs` and set it to `1s`
* Use `retryMaxCount: -1` as "retry indefinitely"
* Use `retryMaxCount: -2` as "do not retry"

**Comment by delaneyj** [comment]
`retryMaxCount:Number.MAX_SAFE_INTEGER` is in practice infinite
`retryMaxCount:0` is do not retry
