### ISSUE TITLE
Packages created by https://data-star.dev/bundler can't be imported as modules

### ISSUE THREAD

**Issue by stefanohrmann** [starfederation/datastar#403]
The documentation for the [Javascript API](https://data-star.dev/reference/javascript_api) recommends for edge cases to import Datastar as a module like the following:

```html
<script type="module">
    import { Datastar } from 'datastar.js'
    
    Datastar.apply(document.body)
</script>
```

If I create a package with the [Bundler](https://data-star.dev/bundler) then the `datastar.js` is created **without** the module syntax.

I think the reason for the missing module syntax is the missing option for `Format: api.FormatESModule` here:

https://github.com/starfederation/datastar/blob/8c5edc7ee73b1a72f10ec558825776090d8d0fee/site/routes_bundler.go#L311-L323

The release process creates a `datastar.js` file too and copies it to https://github.com/starfederation/datastar/blob/main/bundles/datastar.js and this file has the module syntax, because the option for `Format` is set:

https://github.com/starfederation/datastar/blob/8c5edc7ee73b1a72f10ec558825776090d8d0fee/build/run.go#L61-L76

**Comment by bencroker** [comment]
Thanks for the detailed report! I’ve raised a PR at https://github.com/starfederation/datastar/pull/406.
