### ISSUE TITLE
Support for all Input Types

### ISSUE THREAD

**Issue by jmcudd** [starfederation/datastar#405]
Not all of the [input types](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) are supported. For example, data-bind does not work for the color input.

**Comment by bencroker** [comment]
This works for me. Please provide a test case that shows it not working.

```html
<input data-bind-color type="color">
<pre>Color: <code data-text="color.value"></code></pre>
```

![screenshot-5UIZAfHK@2x](https://github.com/user-attachments/assets/392a02e5-149e-429b-8362-9c4d4f5dd2bb)
