### ISSUE TITLE
Rename `data-store` to `data-signals`

### ISSUE THREAD

**Issue by delaneyj** [starfederation/datastar#42]

**Comment by bencroker** [comment]
Let’s be sure about this before committing, as this is THE FIRST THING people are introduced to when approaching Datastar.

**Comment by bencroker** [comment]
My thinking is that it is still valuable to talk about a “store” of signals. If we remove `data-store` then there is just a collection of signals that exist somewhere, and it makes explaining things like merging signals into <something> kind of awkward.

An alternative might be `data-state`, but this feels no better than `data-store`.

Interestingly, the Svelte docs explain the concept of a “store” without once using the word “signals”.
https://svelte.dev/docs/svelte/stores

![screenshot-8JzvV62k@2x](https://github.com/user-attachments/assets/26bbdcf3-94c9-4c59-a78d-057a2d9057b7)
