### ISSUE TITLE
History manipulation

### ISSUE THREAD

**Issue by Superpat** [starfederation/datastar#43]
I'd like to revamp the datastar-redirect event so it allows us to interact with the History api.

I'd rename datastar-redirect to datastar-history with the following possible options:
```
data: method pushState | replaceState
data: url string
data state json
```

```
data: method go back | forward | number
```

```
data: method redirect
data: url string
```

Any thougths on this ? I'll start working on a pr for this pretty soon.

**Comment by delaneyj** [comment]
We are discussing on Discord, but for posterity.  I'm super wary of interacting with the History API as it break core tenants of HATEOAS.  Cookie/flashes is the best approach in most situations.  I think hx-push and its support attributes is a major place where HTMX jump the shark.  Will be looking for more info before accepting a PR in this vein.

**Comment by Superpat** [comment]
So I was able to do exactly what I needed without needing the history API. 

1. The client initiates a datastar post request to the server
2. The server sets some state in a cookie, then starts to stream sse to the client. During the stream it creates a new ressource from the post data and then redirects the client to the page that corresponds to that ressource.
3. The client receives the redirect and issues a get request for the new ressource.
4. The server receives the get request, gets some state from the previously set cookie and sends the html page, prepopulating one of it's elements with data-on-load="$signal = 'some state'; $$post('/somepostrequest')"
5. The client renders the page and initiates a new post request on load
6. The servers receives the request, deletes the cookie then starts streaming sse to the client

Now step 6 could of just read the cookie and I did not need to set a signal in step 4 before the on load, but the element also has an on click for the same route and I didnt want to have to change much code in the route.

I'll close this issue to be reopened if somebody sees the need for this kind of api.

**Comment by pdf** [comment]
> I'm super wary of interacting with the History API as it break core tenants of HATEOAS. Cookie/flashes is the best approach in most situations.

Could you expand on the reasoning here? Wanting to utilize URLs for client navigation/permalinks without completely reinitializing the client doesn't seem like an unreasonable desire, and I'd think the data store approach taken by datastar would lend itself pretty neatly to interacting with History.

**Comment by sbrow** [comment]
I don't understand how storing the state of history information on the server-side is any more or less HATEOAS than storing it on the client side. Either way, you're not saving it in the form data...

Quite Disappointing. I was trying out datastar as a HTMX+Alpine replacement, but without the ability to replace the functionality of `hx-push-url="true"`, routing is much more difficult :'(

**Comment by bencroker** [comment]
@sbrow this is an old issue. If you just want to push a URL onto onto the history stack, you can do it using `history.pushState`.

```html
<button data-on:click="history.pushState({}, '', url)">
```

Or from the backend:

```go
sse.ExecuteScript(`history.pushState({}, '', url)`)
```

See https://data-star.dev/guide/datastar_expressions
