### ISSUE TITLE
Auto scrolling should interrupt on user scroll

### ISSUE THREAD

**Issue by Superpat** [starfederation/datastar#62]
When setting data-scroll-into-view on an element and then streaming events that add fragments to that element the ui will keep that element in view. While this is desired most of the time, it also overrides user scrolling, so the user cant scroll to another part of the page while the events are still streaming. 

We need to be able to interrupt the auto scrolling when the user manually scrolls. We might also want to make it possible to resume auto scrolling if the element with the data-scroll-into-view is intersecting with the ui.

**Comment by Superpat** [comment]
This might work with a scrollIntoView action. @delaneyj is working on it already.

```
<div>Conversation
  <ol>
    <li>Message</li>
  </ol>
  <input data-on-change="$$post(...)" data-intersects.full="$$scrollIntoView('vend', 'instant')"  />
</div
```

**Comment by delaneyj** [comment]
There is an [async-actions-attributes](https://github.com/delaneyj/datastar/tree/async-actions-attributes)  branch with a possible impl for this

**Comment by Superpat** [comment]
So ultimately I got this to work through a combination of signals and events.

This example shows a stream of events that gradually make the message list longer than the viewport. Automatically scrolling down to the most recently appended elements while still allowing users to scroll up. The autoscroll resumes once the user scrolls all the way down. 

```
<div 
  data-ref="conv"
  data-store="{_atBottomBeforeLoad: true, _isAtBottom: true}"
  data-on-scroll="$_isAtBottom = ~conv.scrollTop + ~conv.clientHeight >= ~conv.scrollHeight"
  class="overflow-y-scroll"
>
  <ol id="messageList" data-scroll-into-view.vend.instant>
    <li>Message 1</li>
  </ol>
  
</div>
<input data-on-change="$$post(...)" />
```

And the following sse event in response to the input on change post

```
event: datastar-fragment
data: selector #messageList
data: merge append_element
data: fragment <li data-on-load="$_isAtBottom  ? $$scroll('#messageList', {behavior: 'instant', block: 'end', shouldFocus: false})">Message 2</li>
```

The `behavior: 'instant'` is pretty crucial or you get a race condition when there's too many append_element events in a row. There might be a better way to do this, but I'm pretty happy with it right now.
