### ISSUE TITLE
Reference page needs to be improved

### ISSUE THREAD

**Issue by Superpat** [starfederation/datastar#69]
We dont reference the possible datastar-events and some actions in plugins are not referenced either, like the `$$scroll` action in the visibility plugins.

**Comment by Superpat** [comment]
Just realized that the events are in the backend plugin page, but the event for datastar-signal is not documented.

**Comment by Superpat** [comment]
@delaneyj assigned you since I've yet to use datastar-signal

**Comment by delaneyj** [comment]
You have now @Superpat  :smile:
