### ISSUE TITLE
Move data-ref to signals

### ISSUE THREAD

**Issue by delaneyj** [starfederation/datastar#73]
`ctx.refs` exists because datastar at the time didn't "pollute" the store.  now that `_dsPlugins` is a namespace it should move over.

**Comment by Superpat** [comment]
In any case, any element with an ID is accessible by the global scope.

As you can see in the lower image, this is the console output of clicking on the div.

![image](https://github.com/delaneyj/datastar/assets/4533283/2bff6329-286f-447f-82ea-20113281d6d2)

**Comment by delaneyj** [comment]
true, but you want to be able to access via actions
