### ISSUE TITLE
Consider removing memes from docs

### ISSUE THREAD

**Issue by arnoson** [starfederation/datastar#8]
First of all, thanks for the great tool! This solves most of my issues with alpinejs/htmx and finally there is a htmx-like tool with a typescript codebase :)

When I'm reading the docs I find it hard to concentrate on the text because the memes play in loops. Maybe you could only use them on the landiing pages/essays/examples but keep the docs a bit more focused? Or add an option to disable them, similar to a dark/light mode toggle.

**Comment by delaneyj** [comment]
In the middle of a revamp that does just that

**Comment by delaneyj** [comment]
@arnoson  https://data-star.dev is now meme free

**Comment by arnoson** [comment]
great, thanks for the info!
