### ISSUE TITLE
CDN import not working

### ISSUE THREAD

**Issue by AxelRHD** [starfederation/datastar#9]
Hi, I just found your incredible framework and and decided to give it a try.

I use GO with gin (and gomponents for rendering of HTML).

HTML gets rendered, but it seems, that your library does nothing.

This is the HTML code:
![image](https://github.com/delaneyj/datastar/assets/16512322/b59389f1-1a2e-4b21-b6da-a816c948aa4c)

And this is the result:
![image](https://github.com/delaneyj/datastar/assets/16512322/bbfb06a2-64f0-499a-8bf5-21ed9f7dfcd2)

I also tried the counter-example, but that didn't work neither.

Can you tell me, where the problem is?

Thanks.

**Comment by delaneyj** [comment]
Sorry, things are in flux....

Originally you had to iniate after you included, however change to auto inject since even with all plugins its ~10kb.

Try
```html
<script src="
https://cdn.jsdelivr.net/npm/@sudodevnull/datastar@0.7.0/dist/datastar.min.js
"></script>
```

**Comment by AxelRHD** [comment]
Thank you. I will give it a try.

**Comment by delaneyj** [comment]
@AxelRHD  I'm finishing up a new website and hopefully better docs.  Don't hesitate to reach out on HTMX discord on the Datastar channel
