### ISSUE TITLE
Store values starting with underscores should not be sent to the server

### ISSUE THREAD

**Issue by nonnorm** [starfederation/datastar#97]
The intended behavior of store values starting with underscores (for instance `_dsPlugins`) is that they will be client-side-only and will not be sent to the server with requests. However, in every example I've tried on the website, `_dsPlugins` is getting sent with each request. In the "Store Changed" example, where additional local state is set, that state is also being sent to the server. I have not yet tested this locally, but I would expect the behavior to be the same as on the website.

**Comment by gocmarek** [comment]
Maybe I'm missing something that is in the core of the concept of this nice lib, but I would prefer to leave it to programmer what should be send to server. What about to make create a attribute (like hx-vars) and only this will be send to server?

**Comment by delaneyj** [comment]
You already have that. Just add an _ to the signal name and it won't be sent.

**Comment by gocmarek** [comment]
I see. Thanks a lot for answer.
